import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

/**
 * Generate PDF report from BIM Health data
 */
export class ReportGenerator {
  
  /**
   * Generate PDF report
   */
  static async generatePDF(reportData: any, outputPath: string): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        const stream = fs.createWriteStream(outputPath);

        doc.pipe(stream);

        // Header
        doc.fontSize(24).text('BIM Health Report', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
        doc.moveDown(2);

        // Project Info
        if (reportData.projectInfo) {
          doc.fontSize(16).text('Project Information', { underline: true });
          doc.moveDown(0.5);
          doc.fontSize(11);
          doc.text(`Project Name: ${reportData.projectInfo.name || 'N/A'}`);
          doc.text(`File Name: ${reportData.fileName || 'N/A'}`);
          doc.text(`File Size: ${reportData.fileSize || 'N/A'}`);
          doc.moveDown(1.5);
        }

        // Summary
        if (reportData.summary) {
          doc.fontSize(16).text('Summary', { underline: true });
          doc.moveDown(0.5);
          doc.fontSize(11);
          doc.text(`Total Elements: ${reportData.summary.totalElements || 0}`);
          doc.text(`Total Warnings: ${reportData.summary.totalWarnings || 0}`);
          doc.text(`Total Errors: ${reportData.summary.totalErrors || 0}`);
          doc.moveDown(1.5);
        }

        // Categories
        if (reportData.categories && reportData.categories.length > 0) {
          doc.fontSize(16).text('Elements by Category', { underline: true });
          doc.moveDown(0.5);
          doc.fontSize(10);
          
          reportData.categories.forEach((cat: any) => {
            doc.text(`• ${cat.name}: ${cat.count} elements`);
          });
          doc.moveDown(1.5);
        }

        // Warnings
        if (reportData.warnings && reportData.warnings.length > 0) {
          doc.addPage();
          doc.fontSize(16).text('Warnings', { underline: true });
          doc.moveDown(0.5);
          doc.fontSize(9);
          
          reportData.warnings.slice(0, 50).forEach((warning: any, index: number) => {
            doc.text(`${index + 1}. ${warning.description || warning.message || 'Unknown warning'}`);
            doc.moveDown(0.3);
          });
          
          if (reportData.warnings.length > 50) {
            doc.text(`... and ${reportData.warnings.length - 50} more warnings`);
          }
        }

        // Errors
        if (reportData.errors && reportData.errors.length > 0) {
          doc.addPage();
          doc.fontSize(16).text('Errors', { underline: true });
          doc.moveDown(0.5);
          doc.fontSize(9);
          
          reportData.errors.slice(0, 50).forEach((error: any, index: number) => {
            doc.text(`${index + 1}. ${error.description || error.message || 'Unknown error'}`);
            doc.moveDown(0.3);
          });
          
          if (reportData.errors.length > 50) {
            doc.text(`... and ${reportData.errors.length - 50} more errors`);
          }
        }

        // Footer
        doc.fontSize(8).text('Generated by BIM Health Report System', 50, doc.page.height - 50, {
          align: 'center'
        });

        doc.end();

        stream.on('finish', () => {
          console.log('✅ PDF generated successfully');
          resolve(outputPath);
        });

        stream.on('error', (err) => {
          console.error('❌ PDF generation error:', err);
          reject(err);
        });

      } catch (error) {
        console.error('❌ PDF generation failed:', error);
        reject(error);
      }
    });
  }

  /**
   * Generate HTML report
   */
  static generateHTML(reportData: any): string {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>BIM Health Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    h1 { color: #2563eb; }
    h2 { color: #1e40af; border-bottom: 2px solid #2563eb; padding-bottom: 5px; }
    .summary { background: #eff6ff; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .warning { color: #f59e0b; }
    .error { color: #ef4444; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
    th { background: #2563eb; color: white; }
  </style>
</head>
<body>
  <h1>BIM Health Report</h1>
  <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
  
  <div class="summary">
    <h2>Summary</h2>
    <p><strong>Total Elements:</strong> ${reportData.summary?.totalElements || 0}</p>
    <p><strong>Total Warnings:</strong> <span class="warning">${reportData.summary?.totalWarnings || 0}</span></p>
    <p><strong>Total Errors:</strong> <span class="error">${reportData.summary?.totalErrors || 0}</span></p>
  </div>

  ${reportData.categories && reportData.categories.length > 0 ? `
  <h2>Elements by Category</h2>
  <table>
    <tr><th>Category</th><th>Count</th></tr>
    ${reportData.categories.map((cat: any) => `
      <tr><td>${cat.name}</td><td>${cat.count}</td></tr>
    `).join('')}
  </table>
  ` : ''}

  ${reportData.warnings && reportData.warnings.length > 0 ? `
  <h2>Warnings (${reportData.warnings.length})</h2>
  <ul>
    ${reportData.warnings.slice(0, 100).map((w: any) => `
      <li class="warning">${w.description || w.message || 'Unknown warning'}</li>
    `).join('')}
  </ul>
  ` : ''}

  ${reportData.errors && reportData.errors.length > 0 ? `
  <h2>Errors (${reportData.errors.length})</h2>
  <ul>
    ${reportData.errors.slice(0, 100).map((e: any) => `
      <li class="error">${e.description || e.message || 'Unknown error'}</li>
    `).join('')}
  </ul>
  ` : ''}

  <hr>
  <p style="text-align: center; color: #666; font-size: 12px;">
    Generated by BIM Health Report System
  </p>
</body>
</html>
    `;
  }
}
